language: java

jdk:
  - openjdk8
services:
  - docker
addons:
  sonarcloud:
    organization: tupichkindenis
    token:
      secure: "$SONAR_TOKEN"
before_install:
  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8-jdk-alpine
script:
  - cat $HOME/.m2/settings.xml
  - mvn deploy
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=tupichkindenis_cicd-applied-to-spring-boot-java-app
