language: java

jdk:
  - openjdk8

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8-jdk-alpine

script:
  - cat $HOME/.m2/settings.xml
  - mvn deploy

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=tupichkindenis_cicd-applied-to-spring-boot-java-app

addons:
  sonarcloud:
    organization: "tupichkindenis"
    token:
      secure: "mnZKCsnasVCBHfyXQd5Zx0OYlbczKXC7MxdASsNHjQ6XLvsRWLaEVj3P1/azuAD2pZqTTXSx4cdnPpwNe/a5YjI8IhyL7fGCR2ioPrpB5FSDOVCbIMBr0xaTEaUUo48M9Vl/0zEYuJhHocaMBPhFnymDFdCxb4f9bPFBnyhbLdYcu9UT5a8go6YXlD2vD+iRwxD6jR82WVQ9XdDJ+cmiNY9gB9qgwTe5tN+GKc6qp18RmPv06Sk08yUyhl5tlXPUP/QN/hl57WKHlAmmgwOc752TvXFCcSm5MuvS9FGbRtQ8t5MYP0H4K1LTHm5VfvV3EtPrZe1WlaAt6IGYcgwnLqspQmirFZrv5Pib/dQRUxAfDhAlD2R0GzcvWvmUiXMAY6To+dZlETIenllTP3T0eLN6wI5EG6VpJWqFfK6zcGURcyWQo8unWIf50w3AfpNyNOxwQZ08UtAPPUbO66vMfN1unPcqgusIIHTdqVGouTnYGjgsiQkKVpphmAvkbKH6XBJXGnH0A5r5uDWYW2xPID9X2nKLikZdy3xdp/HJ15QLGGvMhbpdOuYTJGa+aGcQ4plIacMIK84kLYAmteKpe1gQ2UpGN/G9lQxXzmG1VV4EK02IcrT57bnW6UxYKkJsA/mffBETvy9El01AdW1m3m76YbQ21PyqwsQ3IeC7JoI="


