language: java

jdk:
  - openjdk8

services:
  - docker

# SonarCloud
addons:
  sonarcloud:
    organization: "tupichkindenis"
    token:
      secure: "SeJJvytAsYrHxj23gkDn00nzxUcAeorVLtxL3x6SMLvT136H2gznFe1nGSa7eoPvtrmYzvIGUCXRppHA8+y8uWrOMrpm7mp1W/GhnMV0cEw5HHZZftS8C3QD3t81V9aZyqXcVWmPwvjVv4c4ysHT27ihu5srfk6F0nZm9/LHXBnvR+pXkAaPO+vWIjWV+FuEYbI/RFvyyEizmCsqn3aiBpHvWy65+0corKNIAQusck1mHWnmoy5+epxpSLnBcr2xvR94VZNBuWSLw+WiZZPudQ99Tuo6hWG0gf24wCR2UD1xv8W/lA2fi3LZBJhQp1GXy2aV9VptbApqGqJU1badbtOjA3jHa1iU0x6ijSQX7vPzAmgYUpZX+/MJY870tG5eVUvH5r6rkXKR9/kOGrPwvtRQt9Q9jtKCP9ZKWErsNytkicFPgN5usMVYaKyXzdBExnq4Iq6bViWDNstAXMChTulvDN5oiG4VMztKsZT+OWHWPNW1wMh3IfXRm61yzw0TF7e/EDpC9haiY9HQXoyZItiyjLk81ivHYh8QlCRLezDUGMXfnX5KofYVxU3gtZzuap6Y0L5jE/veWnrXBsZYgxlBk51ZO4DWRyz0xXTLTZE0KHeEqQiEtbxAY2iM+Zbh7yVpzwFMIBjKePna2Ma23QpAFblbmrt8uD6MV+OKtkc="

before_install:
  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8-jdk-alpine

script:
  - cat $HOME/.m2/settings.xml
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=tupichkindenis_cicd-applied-to-spring-boot-java-app -Dsonar.organization=tupichkindenis -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=e3472f258297bfd492d841279f18cf4ca0511206
#  - mvn deploy

after_success:
  - bash <(curl -s https://codecov.io/bash)
